services:
  tokka:
    container_name: tokka
    build:
      context: .
      dockerfile: build/Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "7805:7805"
      - "7806:7806"
    volumes:
      - ./tokka.yaml:/app/tokka.yaml
    environment:
      TOKKA_CONFIG: ./tokka.yaml
